### ISSUE TITLE
Going to admin page results in traceback

### ISSUE THREAD

**Issue by murrown** [OSU-Net/cyder#1036]
>https://cyder.oregonstate.edu/administration/ or /administration on your dev instance should drop some message about "UserProfile matching query does not exist."

**Comment by murrown** [comment]
I can't reproduce this error locally, so I'm not sure what's causing it.

**Comment by akeym** [comment]
did you pull a copy of the production database when testing?

**Comment by murrown** [comment]
Good call. Something seems to be wrong with one of the users, and they don't have a `UserProfile` associated with them.

**Comment by akeym** [comment]
created necessary userprofile.. fixed it.
