### ISSUE TITLE
Remove all redundant/unneccesary workgroups

### ISSUE THREAD

**Issue by kiwim0n** [OSU-Net/cyder#126]
When we implemented Maintain 10+ years ago, we inadvertently duplicated all subnet options as workgroup options as well. The workgroups can be removed if they only have the following options set: subnet mask, gateway.  Those options are set at the subnet, and there is no need for the workgroup. The hosts can be assigned to the "default" dummy workgroup.

**Comment by akeym** [comment]
A large chunk of these were removed, but there are some remaining ones that can be removed if time permits
