### ISSUE TITLE
Display DHCP build in interface

### ISSUE THREAD

**Issue by murrown** [OSU-Net/cyder#152]
In the interface, from the network detail view, we can reach a "DHCP Build Output" page that displays that network's DHCP build. Other objects, such as Containers, can generate builds too. Do we want to include these in the interface as well? The objects that can do this so far, contingent on https://github.com/OSU-Net/cyder/issues/151, are Containers, Workgroups, Networks, Views, and Vrfs.

**Comment by akeym** [comment]
I kinda don't care about this at all.  I'll be syncing the build output to a server that DCAs have access to so they can view it if need be.

**Comment by akeym** [comment]
@kiwim0n - do we really need this feature?

**Comment by kiwim0n** [comment]
No. 

-Kirsten
