### ISSUE TITLE
Some static hosts aren't in static ranges in Maintain

### ISSUE THREAD

**Issue by drkitty** [OSU-Net/cyder#323]
Some static hosts in Maintain are enabled but have an IP that isn't in a static range. Here is the full list, as returned by some migration stuff I just wrote:

```text
10.193.3.2
128.193.10.26
128.193.10.206
128.193.172.1
10.192.113.254
10.192.136.63
10.196.32.7
10.196.0.2
10.196.16.2
10.196.8.4
10.192.78.254
10.194.126.71
10.192.131.2
10.196.24.7
10.196.16.7
10.196.8.7
10.196.32.6
140.211.0.130
131.252.152.55
140.211.70.3
128.193.10.34
10.112.52.4
128.193.10.18
128.193.116.2
10.214.144.2
10.192.126.130
69.59.209.50
```

We have a few options here:

a. (in Maintain) put each of these hosts into a static range
b. (in Maintain) disable each of these hosts
c. during migration, disable any static host that's not in a static range
d. during migration, die if a static host isn't in a static range (<em>current behavior</em>)
e. give up on trying to disallow static interfaces in dynamic or non-existent ranges

**Comment by akeym** [comment]
superceeded
