### ISSUE TITLE
Using tablefy to show the main object in a detail view is bizarre

### ISSUE THREAD

**Issue by drkitty** [OSU-Net/cyder#446]
There's really no reason that the main object's information should be in a table, and plenty of reasons why it shouldn't, of which I will list two:
- Tables are most useful when you have multiple rows, which is not the case here.
- Some models have fields or tablefy columns with very long values, which are (or should be) shown in full in the detail view. Putting them in a table decreases the width of each field, requiring some fields to be wrapped that wouldn't need to be if they were not in a table. This is a usability issue.
    - (e.g. `Range.description` from #415, `Range.dhcpd_raw_include`, and the "Range" column of the dynamic interface view)

**Comment by murrown** [comment]
resolved by https://github.com/OSU-Net/cyder/issues/446
