### ISSUE TITLE
A system with more than one dynamic interface breaks the DHCP config

### ISSUE THREAD

**Issue by drkitty** [OSU-Net/cyder#543]
If the system has an empty name, the range's domain is used as the hostname of the `host` declaration for each dynamic interface on the system; if the system's name is non-empty, the name is prepended to the range's domain (with a dot in between). Either way, if there is more than one dynamic interface on the system, those interfaces have duplicate hostnames, which is not allowed.

Here are the two solutions I can think of at the moment:
- Disallow more than one dynamic interface on a system.
- Append a unique string to each dynamic interface's hostname in a system so that the hostnames are unique.

**Comment by murrown** [comment]
resolved by https://github.com/OSU-Net/cyder/pull/864
