### ISSUE TITLE
Scheduling a rebuild for an SOA can cause an exception

### ISSUE THREAD

**Issue by murrown** [OSU-Net/cyder#547]
This seems problematic because, during builds, we sometimes attempt to save an SOA (for some reason). If this raises an exception, we schedule the SOA for a rebuild... however, scheduling a rebuild requires us to save the SOA, which raises another exception. I'm not sure if this is a real issue, but it's confusing nonetheless.

In this specific example, I'm getting the exception:
```
By changing this domain's SOA you are attempting to create a zone whose root domain has no NS record.
```

**Comment by akeym** [comment]
I suppose I don't fully understand the issue here.  When would this actually occur?  Or is it still an issue?

**Comment by murrown** [comment]
I guess this is really a non-issue because there's nothing that can be done about it. There's always the possibility that some unknown element is going to raise an error in the `schedule_rebuild` routine. But since it hasn't caused any problems yet we're probably fine.
