### ISSUE TITLE
Automatically rearrange domains when creating records

### ISSUE THREAD

**Issue by drkitty** [OSU-Net/cyder#731]
```irc
14:01:37 <@drkitty> So if we have a CNAME whose label is 'foo' and whose domain's name is 'example.com', should a Cyder admin be able to create a domain named 'foo.example.com', automatically setting the CNAME's label to '' and its 
                    domain to the newly created foo.example.com Domain?
14:03:53 < akeym> seems like the right thing to do
```

This would apply to all DNS records with a `label` and `domain`. Maintain migrations already do this, but it would be nice to support it from the web interface and the ORM as well.

**Comment by murrown** [comment]
Currently, the user can't create domains if a record with that name already exists. If necessary, we can just delete the record and create the domain manually, and this would be a huge hassle to implement, so I'm just going to clsoe this.
