### ISSUE TITLE
Eliminate uncertainty about permissions

### ISSUE THREAD

**Issue by drkitty** [OSU-Net/cyder#769]
[`cyder.core.cyuser.backends`](https://github.com/OSU-Net/cyder/blob/4ecce80/cyder/core/cyuser/backends.py) has sixteen occurrences of the comment `# ?`. If the lines in question are correct (as I assume they are), the comments should be removed.

**Comment by murrown** [comment]
Resolved by https://github.com/OSU-Net/cyder/pull/812
