### ISSUE TITLE
Enabled dynamic interfaces with the same hostname can exist and will result in invalid DHCP configs

### ISSUE THREAD

**Issue by drkitty** [OSU-Net/cyder#806]
If we have some system s1 with dynamic interface d1 and some other system s2 with dynamic interface d2, where s1.name == s2.name and d1.range = d2.range, d1 and d2 will have identical hostnames. If they both have `dhcp_enabled` True, they both generate host declarations with the same hostname, causing the configuration file to be invalid.

**Comment by murrown** [comment]
It seems strange to me that system name is being used in the first place. What if a system simply has two dynamic interfaces in the same range?

**Comment by drkitty** [comment]
That case (among others) is covered by issue #543, which will be resolved by PR #635.

**Comment by drkitty** [comment]
We could put the MAC address and the range name in the hostname, I suppose. Dynamic interfaces are unique by range and MAC address. It would slow down the DHCP builder even more, though.

**Comment by murrown** [comment]
MAC address instead of system name? I'm not sure I understand how that would be slower, since system name is a foreign field. But I thought the main problem is that it would make it completely impossible to compare builds if we did that.

**Comment by drkitty** [comment]
Building would be slower because it would require slightly more string formatting and an additional attribute lookup. There would still be one foreign key lookup (range instead of system). It would require us to compare config files in a different way, although I don't think it would be terribly difficult.

**Comment by drkitty** [comment]
Oh, we could do range `id` instead. I see.

**Comment by murrown** [comment]
Builds would be less readable, but I don't think that readability is a concern for our client.

**Comment by drkitty** [comment]
I've never heard anything about people wanting to read the DHCP config. It's probably fine, although I guess it could make it more difficult for *us* to debug issues involving the config file.

**Comment by murrown** [comment]
Resolved by https://github.com/OSU-Net/cyder/pull/864
