### ISSUE TITLE
Pressing the enter key in an object form causes a double submit

### ISSUE THREAD

**Issue by drkitty** [OSU-Net/cyder#809]
If it's a creation form, this often causes a duplicate object error to be shown in the form during the split second between when the browser receives the second (failure) response and when the first (success) response causes the page to be refreshed.

**Comment by church29** [comment]
I will be solving this in https://github.com/OSU-Net/cyder/pull/804 because it was interfering with functionality in there. The issue that has caused all of this is application.js, I forgot it existed and everything was working around it causing a lot of colliding code.

**Comment by drkitty** [comment]
**Resolved by PR #804**, although that pull request introduced another problem. See issue #846.
