### ISSUE TITLE
A hyphen does not appear to negate a search phrase

### ISSUE THREAD

**Issue by drkitty** [OSU-Net/cyder#828]
The hyphen doesn't appear to be handled specially at all. It's just searched for along with the rest of the word it's connected to.

For instance, `emt` returns a few results, whereas `-emt` returns nothing.

**Comment by jwasinger** [comment]
I'll check this out as I'm currently working on reformatting the search help page.

**Comment by akeym** [comment]
An exclamation point negates terms.  Update the documentation please.
