### ISSUE TITLE
"Select Free IPv4 IP" is slow in certain cases

### ISSUE THREAD

**Issue by drkitty** [OSU-Net/cyder#829]
The cause is unknown at the moment. I'm guessing there's an inefficient and unoptimizeable database query involved somewhere.

**Comment by drkitty** [comment]
The culprit appears to be `Range.get_next_ip()`.

**Comment by murrown** [comment]
That function is pretty crudely written. That could be optimized a bit by combining the records' IP addresses into a single list or set of used IP addresses. There are probably further optimizations, as well.

**Comment by akeym** [comment]
Aren't there libraries that we could use that have these sort of functions already written and optimized?  Failing that, it seems that if we just take all the results, put them into a set, and then do the difference on that set and the set of all possible IPs in the range and select the first one in the result... it might be faster?  Is it really the nested for loops that make this function slow, or the queries?

**Comment by murrown** [comment]
For every IP address in the range, the function iterates over every address record, pointer, and interface in the range. It might not be the reason why it's slow, but it's a lot slower than what we could be doing, which is to iterate over each object list once and add all of the IP addresses to a set, then take the first free one. It changes from `O(m*n)` to `O(m+n)`.

**Comment by murrown** [comment]
I don't expect that the queries themselves are all that slow, they aren't particularly large or complex.

**Comment by akeym** [comment]
I'm not sure I've ever had this take longer than a second...
