### ISSUE TITLE
Don't hard-code errno values

### ISSUE THREAD

**Issue by drkitty** [OSU-Net/cyder#831]
In certain cases, we compare the `errno` member of an `OSError` exception to a number to determine what error occurred. We should be comparing against values from the the [`errno`](https://docs.python.org/2/library/errno.html) module instead of hard-coded numbers.

**Comment by jwasinger** [comment]
Fixed.  I only found three instances where this happened so let me know if there are more that I didn't catch.

**Comment by drkitty** [comment]
Incidentally, unrelated issues are generally best resolved in separate branches.

**Comment by jwasinger** [comment]
Okay.  I will do that in the future.

**Comment by drkitty** [comment]
The fix looks good, though.

**Comment by drkitty** [comment]
**Resolved by PR #816.**
