### ISSUE TITLE
Add links to main page

### ISSUE THREAD

**Issue by akeym** [OSU-Net/cyder#834]
Add the following links: (text displayed; link)

Register a new device /core/system/create/
How to use Search /search/help/
Cyder User Guide and Reference http://is.oregonstate.edu/it-infrastructure/net/dns-dhcp/cyder/cyder-user-guide

**Comment by murrown** [comment]
Related issue https://github.com/OSU-Net/cyder/issues/833, resolve in the same pull request probably

**Comment by church29** [comment]
Going to wait until https://github.com/OSU-Net/cyder/pull/804 is merged for this. The system/create page does not exist after it is merged.

**Comment by church29** [comment]
Resolved by https://github.com/OSU-Net/cyder/pull/879
