### ISSUE TITLE
bind config builder puts zones in the config file that don't have zone files

### ISSUE THREAD

**Issue by drkitty** [OSU-Net/cyder#836]
One example is `importfashionwear.com.br`.

**Comment by drkitty** [comment]
Apparently there's at least one use case for this—poisoning a zone (in the private view, of course). The only real problem is that the message printed during the build incorrectly states that the (imaginary) zone file won't be named in the config file; it needs to be there or `bind` will complain.

**Comment by murrown** [comment]
resolved by https://github.com/OSU-Net/cyder/pull/832
