### ISSUE TITLE
Error messages don't show up when creating a CNAME in the global container with missing parameters

### ISSUE THREAD

**Issue by jwasinger** [OSU-Net/cyder#843]
When attempting to create a CNAME record in the global container, no error messages are shown when only values for fields 'Label' and 'Domain' are provided.

**Comment by drkitty** [comment]
If I remember correctly, this is because leaving the container field blank causes an exception in some validation code somewhere, leading to a server error instead of a normal response.

**Comment by murrown** [comment]
Not sure at what point this got fixed, but the form now shows that the container field is required if it is left blank.
