### ISSUE TITLE
Document proper procedure for comparing migrated data

### ISSUE THREAD

**Issue by akeym** [OSU-Net/cyder#845]
Please document the process to properly compare Maintain to Cyder's builds after a migration.  Make sure all necessary scripts are in the repo and up to date.

**Comment by akeym** [comment]
Also could be @drkitty  - can't assign to two people

**Comment by drkitty** [comment]
I wrote something [here](https://github.com/OSU-Net/cyder/wiki/Developer-guide:-Comparing-two-DHCP-configs). Do you need more info or is that good?

**Comment by akeym** [comment]
What about DNS?  Why are there two compare commands, and which is better or what is the difference?

**Comment by drkitty** [comment]
The difference is noted below. Should I add more details about runtime vs readability?

**Comment by akeym** [comment]
maybe? which one do YOU use?

**Comment by drkitty** [comment]
I use `dhcpd_compare2` because I'm proud of it and because it's easier to read.

**Comment by drkitty** [comment]
I'll post a short explanation of how to read the output of `dhcpd_compare2`.

**Comment by murrown** [comment]
Here's what I put together. Let me know if there are any improvements I should make.
https://github.com/OSU-Net/cyder/wiki/Overview:-Step-by-step-DNS-migration

**Comment by drkitty** [comment]
Never mind about `dhcpd_compare`. It's useless. Just use `dhcpd_compare2`.

**Comment by akeym** [comment]
@murrown 

"This will can take several hours."

Is a git repo actually needed for staging?  I thought that was only prod.

dnsdiffchecker is in bin, right?

**Comment by murrown** [comment]
@akeym No, a repo is not needed for staging. Yes, dnsdiffchecker is in bin. I've made the corrections.

**Comment by akeym** [comment]
seems fine to me, closing
