### ISSUE TITLE
Remove inventory attrs from interfaces

### ISSUE THREAD

**Issue by akeym** [OSU-Net/cyder#865]
Inventory attributes should only be available on System objects.

**Comment by drkitty** [comment]
Currently, the only attributes allowed on interfaces are inventory attributes. Should we just get rid of attributes on interfaces altogether?

**Comment by akeym** [comment]
I think so - I suppose there may be some day when we feel we need to add additional attributes for individual interfaces, but I don't see that at this time.

**Comment by murrown** [comment]
Resolved by https://github.com/OSU-Net/cyder/pull/914
