### ISSUE TITLE
Partial MAC searching

### ISSUE THREAD

**Issue by akeym** [OSU-Net/cyder#866]
Feature request

**Comment by murrown** [comment]
works if you remove the `:` delimiters, for some reason

**Comment by drkitty** [comment]
Well, MAC addresses are stored without colons. Can't remember why.

**Comment by kiwim0n** [comment]
Iirc, there is no standard way to write a MAC address. Sometimes it is bare, sometimes with colons, sometimes with dashes. So we store it bare. 

-Kirsten

**Comment by murrown** [comment]
I see. Then, the reason it works without colons, is because the search system automatically detects valid MAC addresses and removes the colons before searching them. However, partial MAC addresses are not valid MAC addresses.

**Comment by akeym** [comment]
This sounds like a user training issue.  Closing.
