### ISSUE TITLE
Renaming a domain doesn't update its records' `fqdn` fields

### ISSUE THREAD

**Issue by drkitty** [OSU-Net/cyder#868]

**Comment by drkitty** [comment]
I'm actually not sure why I thought this was the case. We disallow a user from renaming a domain if the domain has child objects. Maybe some objects that would need their `fqdn` updated aren't considered child objects or something.

**Comment by murrown** [comment]
I'm getting a strange error from renaming a domain. I renamed `smokeinsc.forestry.oregonstate.edu` to `smokeinsc2.forestry.oregonstate.edu`, and now when I try to visit the detail view, it insists that some `Domain matching query does not exist`. I'm guessing this is related, and that one of the records on the detail view is trying to retrieve the domain object under the old name.

**Comment by zeeman** [comment]
I just rediscovered this issue. Possibly related to #918?

**Comment by akeym** [comment]
This isn't a feature we want/need - just disallow modifying existing domain names.

**Comment by murrown** [comment]
Resolved by https://github.com/OSU-Net/cyder/pull/926
