### ISSUE TITLE
What Container is this Interface in?

### ISSUE THREAD

**Issue by akeym** [OSU-Net/cyder#873]
Apparently this is actually a tough question to answer from a user's perspective.  We should add a container column to the static/dynamic interface lists and probably all objects.. and the detail view?  Right now it just doesn't say....anywhere.

**Comment by drkitty** [comment]
Related to issue #808.

**Comment by murrown** [comment]
well how wide do you want the interface list view to be? If a user needs to know the container of an interface in the list view, that means they're in the global container... is that the use case?

**Comment by akeym** [comment]
You're right - the issue is really to do with the global search results, not necessarily that you're in the global container.

**Comment by murrown** [comment]
I see... well, maybe we should take the proposed mouseover feature more seriously then. Until then, maybe adding a container field to the forms and possibly the detail views would suffice for now?

**Comment by murrown** [comment]
Superseded by https://github.com/OSU-Net/cyder/issues/936
