### ISSUE TITLE
Users can edit/delete interfaces not in their container

### ISSUE THREAD

**Issue by akeym** [OSU-Net/cyder#874]
It appears that if a user has rights to a container with a domain, it also has rights to any interfaces that use those domains as well.  Example being - search for 'powern' from global search, some hosts will have tss.oregonstate.edu, some will not.  Make sure you've switched to a user that is not a super user, and doesn't have access to zone.cn_mcc.  The hosts that appear in the search with tss.oregonstate.edu are in cn_mcc - and should not be editable.  For example, if you use cyder.nws.oregonstate.edu to test, become user hammersm and then do the search.  I'm just guessing the cause of this permissions violation is related to domains - I have no solid evidence.

**Comment by murrown** [comment]
I think we can fix this by forcing our permissions check in `backends.py` to make sure that the container of the object and the active container are the same. Will need to investigate further though.

Also need to decide whether we want to continue using the implementation where, users can only edit objects they have permission to if they are in the appropriate container.

**Comment by akeym** [comment]
While that isn't the maintain way of doing things, we need to close this hole before release.  Make 'em select the appropriate container for now.  But the requirement here is that container be shown to the user in the UI.
