### ISSUE TITLE
Detail page info lists need some slight adjustments

### ISSUE THREAD

**Issue by drkitty** [OSU-Net/cyder#880]
- [x] Needs a little more horizontal padding between the field name column and the data column. Maybe something like border-spacing: 16px 0.
- [x] Needs a bit more vertical padding below the info list.
- [x] Objects with a single container should show that container in the info list.

**Comment by murrown** [comment]
The container is shown as of https://github.com/OSU-Net/cyder/pull/940

**Comment by murrown** [comment]
Actually, Systems still do not show their container on their detail view.

**Comment by church29** [comment]
Resolved by https://github.com/OSU-Net/cyder/pull/965
