### ISSUE TITLE
How do we test window sizing and how Cyder renders?

### ISSUE THREAD

**Issue by akeym** [OSU-Net/cyder#931]
Do we just resize our browser windows to test different sizes, or do you set your browser to report different screen sizes in developer mode? @drkitty

**Comment by drkitty** [comment]
I think either would work. I resized my browser window when testing IE stuff.

**Comment by church29** [comment]
I tested it through developer mode.

**Comment by akeym** [comment]
Please continue testing with developer mode and spoofing the reported screen resolution as 1280x1024.
