### ISSUE TITLE
Sanity check FAILED

### ISSUE THREAD

**Issue by akeym** [OSU-Net/cyder#932]
The sanity checks done on outgoing configs appear to use git diff, and should be changed.  If a workgroup or pool is updated with even one entry, hundreds of thousands of lines can "change" according to this method.  A simpler line count should be used.

**Comment by drkitty** [comment]
Should we keep the same default thresholds?

**Comment by akeym** [comment]
Seems fine, I define my own anyway.

**Comment by drkitty** [comment]
Do you think we need separate thresholds for increases and decreases?

**Comment by akeym** [comment]
Maybe?  We're primarily concerned with huge swaths of registrations/records
disappearing

**Comment by drkitty** [comment]
I'd consider this resolved.

**Comment by drkitty** [comment]
**Resolved by PR #957.**
