### ISSUE TITLE
Remove VoIP special stuff

### ISSUE THREAD

**Issue by akeym** [OSU-Net/cyder#945]
This didn't work as expected, and should be removed.  They are looking in to doing LLDP instead of relying on DHCP and special boot ranges/options.

**Comment by drkitty** [comment]
So remove the `VoIP` VRF and don't print `allow members of "VoIP"` in range decls?

**Comment by drkitty** [comment]
@akeym: Clarification needed.

**Comment by akeym** [comment]
yes. And any other voip hackery - think there was some sort of special flag on range objects..

**Comment by akeym** [comment]
The VRF shouldn't forcibly be removed, but any automatic generation of that VRF at setup time should be removed.

**Comment by murrown** [comment]
Resolved by https://github.com/OSU-Net/cyder/pull/972
