### ISSUE TITLE
Remove Auto-Complete from AV forms

### ISSUE THREAD

**Issue by akeym** [OSU-Net/cyder#963]
Replace autocomplete with a dropdown list of available Attributes, sorted.

**Comment by drkitty** [comment]
Do we still need the "Attribute Type" field to filter the list? If not, I can make this a lot simpler.

**Comment by drkitty** [comment]
@akeym: ^

**Comment by akeym** [comment]
I believe its more important for DHCP options/attributes.. but then again, a combined list might not be bad after all, since users won't need to know what type to choose.  Any other implications I'm forgetting?

**Comment by drkitty** [comment]
That's the only one I can think of. There's no effect on the backend. It just simplifies the frontend code.

**Comment by akeym** [comment]
I'm okay with a combined list if we remove "inventory" attributes from network attributes..

**Comment by drkitty** [comment]
Can do.

**Comment by akeym** [comment]
Remove inventory attributes from workgroups as well.. otherwise seems fine

**Comment by drkitty** [comment]
**Resolved by PR #975.**
